import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ 
  weight: ['400','500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{background:"radial-gradient(123.00% 130.00% at 101% -6%,rgb(32, 29, 71),rgb(23, 21, 58) 100%)", backgroundRepeat:'no-reapet'}} className={poppins.className}>{children}</body>
    </html>
  );
}
